/**
 * Gift card catalog data for Card Vault
 */

export const giftCards = [
  {
    id: 'gc-1',
    brand: 'Amazon',
    name: 'Amazon Gift Card',
    denomination: '$50',
    value: 50,
    currency: 'USD',
    category: 'retail',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&h=250&fit=crop',
    description: 'Use at millions of stores worldwide. No expiration.',
    inStock: true,
    popular: true,
  },
  {
    id: 'gc-2',
    brand: 'Apple',
    name: 'App Store & iTunes',
    denomination: '$25',
    value: 25,
    currency: 'USD',
    category: 'digital',
    image: 'https://images.unsplash.com/photo-1611472173362-3f53dbd65d80?w=400&h=250&fit=crop',
    description: 'Music, movies, apps, and more. Redeem in App Store or iTunes.',
    inStock: true,
    popular: true,
  },
  {
    id: 'gc-3',
    brand: 'Google Play',
    name: 'Google Play Gift Card',
    denomination: '$15',
    value: 15,
    currency: 'USD',
    category: 'digital',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop',
    description: 'Apps, games, movies, and books on Google Play.',
    inStock: true,
    popular: false,
  },
  {
    id: 'gc-4',
    brand: 'Starbucks',
    name: 'Starbucks eGift Card',
    denomination: '$20',
    value: 20,
    currency: 'USD',
    category: 'food',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=250&fit=crop',
    description: 'Coffee, food, and merchandise at Starbucks.',
    inStock: true,
    popular: true,
  },
  {
    id: 'gc-5',
    brand: 'Steam',
    name: 'Steam Wallet Code',
    denomination: '$20',
    value: 20,
    currency: 'USD',
    category: 'gaming',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=250&fit=crop',
    description: 'Games, software, and more on Steam.',
    inStock: true,
    popular: false,
  },
  {
    id: 'gc-6',
    brand: 'Netflix',
    name: 'Netflix Gift Card',
    denomination: '$30',
    value: 30,
    currency: 'USD',
    category: 'entertainment',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=250&fit=crop',
    description: 'Redeem for Netflix membership. Stream anywhere.',
    inStock: true,
    popular: true,
  },
  {
    id: 'gc-7',
    brand: 'Xbox',
    name: 'Xbox Gift Card',
    denomination: '$25',
    value: 25,
    currency: 'USD',
    category: 'gaming',
    image: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=250&fit=crop',
    description: 'Games, add-ons, and subscriptions on Xbox.',
    inStock: true,
    popular: false,
  },
  {
    id: 'gc-8',
    brand: 'Spotify',
    name: 'Spotify Gift Card',
    denomination: '$15',
    value: 15,
    currency: 'USD',
    category: 'entertainment',
    image: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=400&h=250&fit=crop',
    description: 'Premium music streaming. Ad-free listening.',
    inStock: true,
    popular: false,
  },
]

export const categories = [
  { id: 'all', label: 'All' },
  { id: 'retail', label: 'Retail' },
  { id: 'digital', label: 'Digital' },
  { id: 'food', label: 'Food & Drink' },
  { id: 'gaming', label: 'Gaming' },
  { id: 'entertainment', label: 'Entertainment' },
]

export function getGiftCardById(id) {
  return giftCards.find((card) => card.id === id) ?? null
}
